version: '3'

services:
  api:
    container_name: projeto-integrador-iv-api
    build: .
    ports:
      - "8000:8000"
    #environment:
    #  - OPENAI_API_KEY=${OPENAI_API_KEY}
    #  - GOOGLEAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      - ./app:/app